{{- if .Values.serviceMonitor.enabled -}}
{{- $fullName := include "sophora-importer.fullname" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: {{ $fullName }}
    labels: {{- include "sophora-importer.labels" . | nindent 8 }}
spec:
    selector:
        matchLabels: {{- include "sophora-importer.labels" . | nindent 12 }}
    endpoints:
        - interval: {{ .Values.serviceMonitor.interval }}
          port: main
          path: /actuator/prometheus
{{- end }}
